version: '2'
services:
  ### Posgres database for inventory
  db-courses:
    container_name: db-courses
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_courses
      POSTGRES_USER: kendev
      POSTGRES_PASSWORD: Test123
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431
  ### MySQL database for Orders
  db-students:
    container_name: db-students
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_students
      MYSQL_USER: kendev
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    expose:
      - 3306